// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreApi.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240825054828_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreApi.Persistence.Models.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AdditionalReportTo1_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AdditionalReportTo1_EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AdditionalReportTo2_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AdditionalReportTo2_EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AppStatusBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<string>("AppStatusBM_ItemNameUsers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BM_BranchID")
                        .HasColumnType("int");

                    b.Property<string>("BM_BranchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BloodBM_ItemID")
                        .HasColumnType("int");

                    b.Property<string>("BloodBM_ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CauseOfSeparation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CauseOfSeparationBM_ItemID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ConfirmationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmationDateApprox")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractualDateFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ContractualDateTo")
                        .HasColumnType("datetime2");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfJoining")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistrictBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<decimal?>("DottedLine2_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DottedLine2_EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DottedLineHR_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DottedLineHR_EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EBS_CostCenterCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EBS_CostCenterID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EBS_CostCenterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EBS_Depot_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EBS_EmployeeCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EBS_InterCompanyCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EBS_LegalEntityCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EBS_LocationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EBS_LocationID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EBS_LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("EBS_OU_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("EBS_OU_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EBS_Region_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeFileLocationBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeFileLocationBM_ItemNameUsers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GenderBM_ItemID")
                        .HasColumnType("int");

                    b.Property<string>("GenderBM_ItemName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrandeBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<string>("GrandeBM_ItemNameUsers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HRMappedRoleId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("HRRoleId")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("HR_BandID")
                        .HasColumnType("int");

                    b.Property<int?>("HR_DeptID")
                        .HasColumnType("int");

                    b.Property<string>("HR_DeptName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HR_DesgID")
                        .HasColumnType("int");

                    b.Property<string>("HR_DesgName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HR_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HR_EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HR_GradeID")
                        .HasColumnType("int");

                    b.Property<bool?>("HoldSalary")
                        .HasColumnType("bit");

                    b.Property<string>("HoldSalaryReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Inactive")
                        .HasColumnType("bit");

                    b.Property<int?>("JobLevelBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<string>("JobLevelBM_ItemNameUsers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LPRPaymentID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("LastUpdateBy")
                        .HasColumnType("bigint");

                    b.Property<string>("LastUpdateByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LegalEntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MappedRoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mgr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MinimumDaysOfConfirmation")
                        .HasColumnType("int");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NationalityInv_CountryID")
                        .HasColumnType("int");

                    b.Property<string>("Phone1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureNameForWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlaceOfPostingBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<string>("PlaceOfPostingBM_ItemNameUsers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceOfPostingPrefixForEmpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<bool>("ProcessForLPR")
                        .HasColumnType("bit");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ReportTo2_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReportTo2_EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ReportToHR_EmployeeID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReportToHR_EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RetireDateActual")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RetireDateApproximate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("RoleID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SF_ID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalaryAccountAcc_BankID")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SalaryAccountAcc_BankName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SalaryScaleBM_ItemIDUsers")
                        .HasColumnType("int");

                    b.Property<string>("SalaryScaleBM_ItemNameUsers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SalarySheetSerialNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("eTIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_area_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_bu_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_func_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_subArea_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_subFunc_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sap_support_code")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
